#!/bin/sh
docker build --build-arg AWSCLI_VER=$AWSCLI_VER \
             --build-arg NOMAD_VERSION=$NOMAD_VERSION \
             --build-arg NOMAD_SHA256=$NOMAD_SHA256 \
             --build-arg NOMAD_ADDR=$NOMAD_ADDR \
             -t $IMAGE_NAME .
